//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package jsonpatch

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in JSONPatches) DeepCopyInto(out *JSONPatches) {
	{
		in := &in
		*out = make(JSONPatches, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONPatches.
func (in JSONPatches) DeepCopy() JSONPatches {
	if in == nil {
		return nil
	}
	out := new(JSONPatches)
	in.DeepCopyInto(out)
	return *out
}
